### ISSUE TITLE
Code voor beelden van kerst elementen

### ISSUE THREAD

**Issue by RukiyaTossou** [RukiyaTossou/user-needs#2]
Zoek op codepen kerst elementen die je kan implementeren 
 Inspiratie van pinterest in figma bij elkaargezet 

![Image](https://github.com/user-attachments/assets/f036f50d-1a2e-4cef-83e6-df9063cc344e)
afbeelding zou als kerstbal kunnen worden weergegeven. 

Achtergrond opties : 

![Image](https://github.com/user-attachments/assets/497b5718-ff05-4cc4-a1f7-64d63067f669)

Verschillende soorten kerst bollen 

![Image](https://github.com/user-attachments/assets/ee372542-9670-4657-a5c9-cfd047f2c538)

De neon is niet goed te zien bij de andere achtergronden met afbeeldingen. Het is wel goed te zien bij de donkere achtergrond

**Comment by RukiyaTossou** [comment]
Vieuwtransition toegevoegd aan de code, geen error meer 

https://github.com/user-attachments/assets/44440378-867c-4828-8334-2f6485e19f9d

```css
.masonry-item {
		break-inside: avoid;
		display: block;
		background-color: #fff;
		border-radius: 50%;
		box-shadow: 4px 4px 6px rgba(0, 0, 0, 0.1);
		margin: 2rem 2rem 2rem 2rem;

		position: relative;
		animation:  rotate-animation linear;
		animation-timeline: view();
		
	}


```

```css

	/* Prefers reduced motion */
	@media (prefers-reduced-motion) {
		.masonry-item {
			transition: none;
		}

		img {
			transition: none;
		}
	}


	/* Keyframes voor de rotatie animatie */
	@keyframes rotate-animation {
		0% {
			transform: rotate(0deg);
		}
		100% {
			transform: rotate(180deg);
		}
	}

```
